- project:
    check:
      jobs:
        - openstack-tox-linters
        - watcher-prometheus-integration
        - devstack-prometheus
    gate:
      jobs:
        - openstack-tox-linters
        - devstack-prometheus

- job:
    name: devstack-prometheus-base
    nodeset: openstack-single-node-noble
    abstract: true
    parent: devstack-base
    description: |
      A minimal DevStack base job to install and configure prometheus and
      node exporter service only.
    required-projects:
      - opendev.org/openstack/devstack-plugin-prometheus
      - opendev.org/openstack/requirements
    vars:
      devstack_plugins:
        devstack-plugin-prometheus: https://opendev.org/openstack/devstack-plugin-prometheus
      devstack_services:
        prometheus: true
        node_exporter: true
      zuul_copy_output:
        /etc/prometheus/prometheus.yml: logs

- job:
    name: devstack-prometheus
    parent: devstack-prometheus-base
    description: |
      A Devstack job to install/configure prometheus and node exporter
      on a single node and exclude cpu metrics
    vars:
      devstack_localrc:
        # Avoid collecting cpu resources.
        NODE_EXPORTER_COLLECTOR_EXCLUDE: "cpu"
