[tox]
minversion = 3.18.0
skipsdist = True
envlist = bashate

[testenv]
usedevelop = False
install_command = pip install {opts} {packages}

[testenv:linters]
description =
    Run style checks.
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files --show-diff-on-failure
